config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, path_names: { sign_in: 'login', sign_out: 'logout' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get '', to: redirect('celebration-events/')
  get 'celebration-events/', to: 'celebration_events#index'
  get 'celebration-events/:id/retry', to: 'celebration_events#retry'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HrMailer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
    <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
        <img class="me-3 pb-1" height="32" src="https://www.pisano.com/hs-fs/hubfs/pisano-logo-header-1.png">
        <span class="mx-1 fs-4">HR Auto Mailer</span>
      </a>
      <ul class="nav nav-pills">
        <li class="nav-item"><a href="/celebration-events" class="nav-link active" aria-current="page">Celebration Events</a></li>
        <% if admin_signed_in? %>
          <li class="nav-item"><%= button_to 'Sign out', '/admins/logout', method: :delete, class: "btn" %></li>
        <% end %>
      </ul>
    </header>
    </div>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  </body>
</html>